// src/commands.js — Slash command handlers
// Registers /standup (opens the Block Kit form modal) and /standup-report
// (weekly summary with blocker trends and team health score).

const { getTeamStatus, generateSummary, hasRealBlocker } = require('./digest');
const { buildStandupForm } = require('../views/standupForm');

/**
 * Calculates team health score as a percentage of responses without blockers.
 * Uses hasRealBlocker to treat "no", "none", "n/a" as no blocker.
 *
 * @param {Object[]} responses — Standup responses
 * @returns {number} Health score percentage
 */
function calculateHealthScore(responses) {
  if (responses.length === 0) return 0;

  const withoutBlockers = responses.filter(
    (r) => !hasRealBlocker(r.blockers)
  ).length;

  return Math.round((withoutBlockers / responses.length) * 100);
}

/**
 * Returns the health emoji for a given score.
 *
 * @param {number} score — Health score (0–100)
 * @returns {string} Emoji character
 */
function healthEmoji(score) {
  if (score >= 80) return '💚';
  if (score >= 50) return '💛';
  return '❤️';
}

/**
 * Deduplicates responses to show only the latest entry per user.
 * Assumes responses are ordered newest-first (from getResponses).
 *
 * @param {Object[]} responses — Standup responses
 * @returns {Object[]} One entry per user (latest only)
 */
function getLatestPerUser(responses) {
  const seen = new Set();
  return responses.filter((r) => {
    if (seen.has(r.userId)) return false;
    seen.add(r.userId);
    return true;
  });
}

/**
 * Builds the Block Kit message payload for the standup report.
 * Clean layout: header, team health line, recent update cards, short summary.
 *
 * @param {Object[]} responses — Standup responses to report on
 * @returns {Object} Block Kit message payload
 */
function buildReportBlocks(responses) {
  // Deduplicate: show only latest entry per user
  const latest = getLatestPerUser(responses);
  const score = calculateHealthScore(latest);
  const emoji = healthEmoji(score);
  const blockerCount = latest.filter((r) => hasRealBlocker(r.blockers)).length;
  const clearCount = latest.length - blockerCount;
  const summary = generateSummary(latest);

  const dateLabel = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const blocks = [
    // Header
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: '📊 Standup Report',
        emoji: true,
      },
    },
    // Date
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Generated:* ${dateLabel}`,
      },
    },
    { type: 'divider' },
    // Team Health — one clean line
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `${emoji} *${score}% Health Score* | ${latest.length} Updates | ${blockerCount} Blockers | ${clearCount} Clear`,
      },
    },
    { type: 'divider' },
    // Recent Updates — clean cards
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: '*📝 Recent Updates*',
      },
    },
  ];

  // Show up to 5 most recent, one card per person
  for (const r of latest.slice(0, 5)) {
    const submittedDate = new Date(r.submittedAt).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
    });

    let card = `👤 <@${r.userId}> — ${submittedDate}\n🎯 Working on: ${r.today || '—'}`;

    // Only show blocker line if it's a real blocker
    if (hasRealBlocker(r.blockers)) {
      card += `\n🛑 Blocker: ${r.blockers}`;
    }

    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: card,
      },
    });
  }

  blocks.push({ type: 'divider' });

  // AI Summary — short 2-3 sentences
  blocks.push({
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: '*🤖 Summary*\n' + summary,
    },
  });

  blocks.push({ type: 'divider' });

  // Footer
  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: '🤖 Generated by StandupIQ',
      },
    ],
  });

  return blocks;
}

/**
 * Registers slash command handlers on the Bolt app.
 * Currently handles /standup-report for weekly team summaries.
 *
 * @param {App} app — The Bolt app instance
 * @param {Function} getResponses — Function that returns stored responses
 */
function setupHandlers(app, getResponses) {
  /**
   * /standup — Opens the standup Block Kit modal directly.
   * Slash commands provide a trigger_id, so the modal can be opened
   * immediately without needing a button click first.
   */
  app.command('/standup', async ({ ack, command, client }) => {
    console.log('✅ /standup command received');

    // Acknowledge immediately — Slack requires this within 3 seconds
    await ack();

    try {
      const modal = buildStandupForm();

      const result = await client.views.open({
        trigger_id: command.trigger_id,
        view: modal,
      });

      console.log(`📋 /standup modal opened — view_id: ${result.view?.id}`);
    } catch (error) {
      console.error('Error opening standup modal:', error.message);
      console.error('trigger_id used:', command.trigger_id);
    }
  });

  /**
   * /standup-report — Weekly summary of standup activity.
   * Shows team health score, blocker trends, individual stats,
   * and an AI-generated summary. Response is visible only to
   * the user who invoked the command.
   */
  app.command('/standup-report', async ({ ack, respond, command }) => {
    try {
      await ack();

      const responses = getResponses();

      if (responses.length === 0) {
        await respond({
          response_type: 'ephemeral',
          text: 'No standup data available yet.',
          blocks: [
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: '📋 *No standup data available yet.*\n\nStandup responses are collected when team members submit the daily form. Check back after some standups have been completed.',
              },
            },
          ],
        });
        return;
      }

      const blocks = buildReportBlocks(responses);

      await respond({
        response_type: 'ephemeral',
        text: 'Standup Report',
        blocks,
      });

      console.log(
        `📋 /standup-report served to <@${command.user_name}> — ${responses.length} response(s)`
      );
    } catch (error) {
      console.error('Error handling /standup-report:', error.message);

      try {
        await respond({
          response_type: 'ephemeral',
          text: 'Sorry, something went wrong generating the report.',
        });
      } catch (respondError) {
        console.error('Failed to send error response:', respondError.message);
      }
    }
  });

  console.log('✅ Slash command handlers registered');
}

module.exports = { setupHandlers, buildReportBlocks, calculateHealthScore, getLatestPerUser };
